# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1


assistant_id: 20241119-222206-ragged-monomer

language: vi

pipeline:
- name: DucklingEntityExtractor
  url: "http://localhost:8000"
  dimensions:
    - time
  locale: "vi_VN"         # Ngôn ngữ tiếng Việt
  timezone: "Asia/Ho_Chi_Minh" 
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  case_sensitive: False
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  tensorboard_log_directory: './tensorboard_logs/model_1_2711'
  tensorboard_log_level: 'epoch'
  constrain_similarities: true
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1



# pipeline:
# - name: DucklingEntityExtractor
#   url: "http://localhost:8000"
#   dimensions:
#     - time
#   locale: "vi_VN"         
#   timezone: "Asia/Ho_Chi_Minh" 
# - name: WhitespaceTokenizer
#   intent_tokenization_flag: False 
#   intent_split_symbol: "_"
# - name: RegexFeaturizer
#   case_sensitive: False
# - name: LexicalSyntacticFeaturizer
# - name: CountVectorsFeaturizer
#   analyzer: char_wb
#   min_ngram: 1
#   max_ngram: 4
# - name: custom_component.svm_classifier.SVMClassifier  
# - name: EntitySynonymMapper
# - name: ResponseSelector
#   epochs: 100
#   constrain_similarities: true
# - name: FallbackClassifier
#   threshold: 0.3
#   ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
